# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"RedisWQ": "00_rediswq.ipynb",
         "sedas_client": "00_utils.ipynb",
         "sedas_get_collections": "00_utils.ipynb",
         "sedas_find_datasets": "00_utils.ipynb",
         "sedas_download": "00_utils.ipynb",
         "sedas_extract": "00_utils.ipynb",
         "convert2cog": "00_utils.ipynb",
         "mosaic2cog": "00_utils.ipynb",
         "cogmosaicbands": "00_utils.ipynb",
         "s3_create_client": "00_utils.ipynb",
         "gb": "00_utils.ipynb",
         "s3_single_upload": "00_utils.ipynb",
         "get_rel_dir_s3_paths": "00_utils.ipynb",
         "s3_upload_dir": "00_utils.ipynb",
         "s3_list_objects_paths": "00_utils.ipynb",
         "s3_list_objects": "00_utils.ipynb",
         "clean_up": "00_utils.ipynb",
         "setup_logging": "00_utils.ipynb",
         "create_uri": "00_utils.ipynb",
         "my_read_method": "00_utils.ipynb",
         "my_write_method": "00_utils.ipynb",
         "pystac_setIO": "00_utils.ipynb",
         "prep_pleiades": "01A_pleiades.ipynb",
         "pleiades_bands": "01A_pleiades.ipynb",
         "pleiades_get_dt": "01A_pleiades.ipynb",
         "pleiades_get_geom": "01A_pleiades.ipynb",
         "pleiades_parsemeta": "01A_pleiades.ipynb",
         "pleiades_get_bbox": "01A_pleiades.ipynb",
         "process_scene": "01B_pleiades_prep_worker.ipynb",
         "level": "01B_pleiades_prep_worker.ipynb",
         "host": "01B_pleiades_prep_worker.ipynb",
         "q": "01B_pleiades_prep_worker.ipynb",
         "logger": "01B_pleiades_prep_worker.ipynb",
         "prep_spot": "02A_spot.ipynb",
         "spot_bands": "02A_spot.ipynb",
         "spot_get_dt": "02A_spot.ipynb",
         "spot_parsemeta": "02A_spot.ipynb",
         "spot_get_geom": "02A_spot.ipynb",
         "spot_get_bbox": "02A_spot.ipynb"}

modules = ["rediswq.py",
           "utils.py",
           "pleiades.py",
           "pleiades_prep_worker.py",
           "spot.py"]

doc_url = "https://tjones1993.github.io/sac_stac/"

git_url = "https://github.com/tjones1993/sac_stac/tree/master/"

def custom_doc_links(name): return None
