# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"sedas_client": "00_utils.ipynb",
         "sedas_get_collections": "00_utils.ipynb",
         "sedas_find_datasets": "00_utils.ipynb",
         "sedas_download": "00_utils.ipynb",
         "sedas_extract": "00_utils.ipynb",
         "convert2cog": "00_utils.ipynb",
         "mosaic2cog": "00_utils.ipynb",
         "s3_create_client": "00_utils.ipynb",
         "gb": "00_utils.ipynb",
         "s3_single_upload": "00_utils.ipynb",
         "get_rel_dir_s3_paths": "00_utils.ipynb",
         "s3_upload_dir": "00_utils.ipynb",
         "s3_list_objects_paths": "00_utils.ipynb",
         "s3_list_objects": "00_utils.ipynb"}

modules = ["utils.py",
           "pleiades.py"]

doc_url = "https://tjones1993.github.io/sac_stac/"

git_url = "https://github.com/tjones1993/sac_stac/tree/master/"

def custom_doc_links(name): return None
