# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://tjones1993.github.io/sac_stac/"

git_url = "https://github.com/tjones1993/sac_stac/tree/master/"

def custom_doc_links(name): return None
