# AUTOGENERATED! DO NOT EDIT! File to edit: 09_cs_stact_catalog.ipynb (unless otherwise specified).

__all__ = ['cs_create_catalog']

# Cell
from datetime import datetime

import pystac

from .utils import pystac_setIO
from .sentinel2 import s2_create_collection


# Cell
pystac_setIO()

# Cell
def cs_create_catalog(collections):

    catalog_id = 'cs-stac'
    catalog_title = 'IPP Common Sensing Geospatial Datasets'
    catalog_description = '''### Geospatial datasets hosted by IPP Common Sensing Project

    A catalog of optical and synthetic aperture radar (SAR) satellite datasets and derived products. Hosted by Satellite Applications Catapult.
    '''
    catalog_extensions = ['eo', 'projection', 'product_definition']

    catalog = pystac.Catalog(id=catalog_id,
                             title=catalog_title,
                             description=catalog_description,
                             stac_extensions=catalog_extensions)

    catalog.add_children([collections])

    return catalog