# AUTOGENERATED! DO NOT EDIT! File to edit: 09_sac_stac_catalog.ipynb (unless otherwise specified).

__all__ = ['ssgp_create_collection', 'sac_create_catalog']

# Cell
from datetime import datetime

import pystac

from .utils import pystac_setIO
from .pleiades import pleiades_create_collection
from .spot import spot_create_collection

# Cell
pystac_setIO()

# Cell
def ssgp_create_collection(child_collections):

    collection_id = 'uksa-ssgp'
    collection_title = 'SSGP-procured VHR Satellite Data over the UK'
    collection_description = '''### UKSA / SSGP Satellite Data

    A collection of Very High Resolution (VHR) optical and synthetic aperture radar (SAR) satellite datasets over the UK. Procured by UKSA under its Space for Smarter Government Programme (SSGP).
    '''

    # initially arbitrary as updated later
    spatial_extent = pystac.SpatialExtent([[-7.57216793459, 49.959999905, 1.68153079591, 58.6350001085]])
    temporal_extent = pystac.TemporalExtent([[datetime(2011, 12, 16), None]])
    collection_extent = pystac.Extent(spatial_extent, temporal_extent)

    collection = pystac.Collection(id=collection_id,
                                   title=collection_title,
                                   description=collection_description,
                                   extent=collection_extent)

    collection.providers = [
        pystac.Provider(name='Airbus Defence & Space', roles=['producer'], url='https://www.airbus.com/space.html'),
        pystac.Provider(name='UK Space Agency', roles=['licensor'], url='https://www.gov.uk/government/organisations/uk-space-agency'),
        pystac.Provider(name='Satellite Applications Catapult', roles=['processor'], url='https://sa.catapult.org.uk/'),
        pystac.Provider(name='Satellite Applications Catapult', roles=['host'], url='https://sa.catapult.org.uk/')
    ]

    collection.add_children(child_collections)

    return collection

# Cell
def sac_create_catalog(collections):

    catalog_id = 'sac-stac'
    catalog_title = 'Catapult-hosted Geospatial Datasets'
    catalog_description = '''### Geospatial datasets hosted by the Satellite Applications Catapult (Catapult)

    A catalog of optical and synthetic aperture radar (SAR) satellite datasets. Hosted by Catapult but often licensed by 3rd parties (i.e. UKSA/SSGP).
    '''
    catalog_extensions = ['eo', 'projection']

    catalog = pystac.Catalog(id=catalog_id,
                             title=catalog_title,
                             description=catalog_description,
                             stac_extensions=catalog_extensions)

    catalog.add_children([collections])

    return catalog