# AUTOGENERATED! DO NOT EDIT! File to edit: 02A_spot.ipynb (unless otherwise specified).

__all__ = ['prep_spot', 'spot_bands', 'spot_get_dt', 'spot_parsemeta', 'spot_get_geom', 'spot_get_bbox', 'spot_bands']

# Cell
import os
from glob import glob
import time
import numpy as np
from datetime import datetime
import json

import xmltodict
import pystac
from pystac import STAC_IO
from pystac.extensions.eo import Band
import geopandas as gpd

from .utils import sedas_client, sedas_find_datasets, sedas_download, sedas_extract
from .utils import cogmosaicbands
from .utils import s3_upload_dir, s3_list_objects_paths, clean_up
from .utils import pystac_setIO, create_uri

# Cell
def prep_spot(sedas_supplierId, inter_dir="/tmp/data/intermediate/",
                  s3_bucket="public-eo-data", s3_dir="uksa-ssgp/spot/"):
    try:
        inter_dir = f"{inter_dir}{sedas_supplierId}_tmp/"
        os.makedirs(inter_dir, exist_ok=True)
        scene_name = sedas_supplierId
        down_zip = f"{inter_dir}{scene_name}.zip"
        scene_dir = f"{down_zip[:-4]}/"
        print(f"{time.strftime('%Y-%m-%d %H:%M:%S')} Preparing {scene_name} within {inter_dir}")
        # find & download
        sedas_scene_res = sedas_client().search_product(sedas_supplierId)[0]
        sedas_download([sedas_scene_res], inter_dir)
        sedas_extract(down_zip, scene_dir)
        # sensor-specific band mosaicing and cogifying
        imgs_ms = glob(f"{scene_dir}*/*/*MS_001*/*.TIF")
        imgs_pan = glob(f"{scene_dir}*/*/*P_001*/*.TIF")
        cogmosaicbands(imgs_pan, 1, imgs_pan[0][:-20])
        cogmosaicbands(imgs_ms, 4, imgs_ms[0][:-20])
        # upload
        s3_upload_dir(scene_dir, s3_bucket, s3_dir)
        print(f"{time.strftime('%Y-%m-%d %H:%M:%S')} Prepared {scene_name} at {s3_dir}{scene_name}/")
        clean_up(inter_dir)
    except Exception as e:
        print(f"{time.strftime('%Y-%m-%d %H:%M:%S')} Failed with {e}")
        clean_up(inter_dir)

# Cell
spot_bands = [Band.create(name='Panchromatic', description='Panchromatic: 450 - 745 nm', common_name='pan'),
              Band.create(name='Blue', description='Blue: 450 - 520 nm', common_name='blue'),
              Band.create(name='Green', description='Green: 530 - 590 nm', common_name='green'),
              Band.create(name='Red', description='Red: 625 - 695 nm', common_name='red'),
              Band.create(name='Near-Infrared', description='Near-Infrared: 760 - 890 nm', common_name='nir')]

# Cell
def spot_get_dt(scene_name):
    return datetime.strptime(scene_name.split('_')[5][:14], '%Y%m%d%H%M%S')

# Cell
def spot_parsemeta(meta_path):
    return xmltodict.parse(pystac.STAC_IO.read_text(create_uri(meta_path)))

# Cell
def spot_get_geom(scene_paths, native_epsg):
    nat_crs = {"init": f"epsg:{native_epsg}"}
    roi_path = [i for i in scene_paths if (i.endswith('1_MSK.GML') * os.path.basename(i).startswith('ROI'))][0]
    roi_uri = create_uri(roi_path)
    g = gpd.read_file(roi_uri)
    g.crs = f"EPSG:{native_epsg}"
    return json.loads(g.to_crs('EPSG:4326').to_json(show_bbox=True))['features'][0]['geometry']

# Cell
def spot_get_bbox(metadata):
    lons = [float(i['LON']) for i in metadata['Dimap_Document']['Dataset_Content']['Dataset_Extent']['Vertex']]
    lats = [float(i['LAT']) for i in metadata['Dimap_Document']['Dataset_Content']['Dataset_Extent']['Vertex']]
    return [min(lons), min(lats), max(lons), max(lats)]

# Cell
spot_bands = [Band.create(name='Panchromatic', description='Panchromatic: 450 - 745 nm', common_name='pan'),
              Band.create(name='Blue', description='Blue: 450 - 520 nm', common_name='blue'),
              Band.create(name='Green', description='Green: 530 - 590 nm', common_name='green'),
              Band.create(name='Red', description='Red: 625 - 695 nm', common_name='red'),
              Band.create(name='Near-Infrared', description='Near-Infrared: 760 - 890 nm', common_name='nir')]