# AUTOGENERATED! DO NOT EDIT! File to edit: 01_pleiades.ipynb (unless otherwise specified).

__all__ = ['pleiades_find_datasets']

# Cell
from .utils import sedas_client, get_sedas_collections

import pandas as pd

# Cell
def pleiades_find_datasets(wkt, startDate, endDate):
    sedas = sedas_client()
    return sedas.search_optical(wkt, startDate, endDate, source_group="Pleiades")